In [1]:
from numpy import *

In [19]:
A=mat([[1,2,3],[4,5,6],[7,8,9]])
B=mat([[1,1,1],[2,2,2],[3,3,3]])
C=mat([3,2,1])
D=mat([[1],[3],[5]])
print('A:\n',A)
print('B:\n',B)
print('C:\n',C)
print('D:\n',D)

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
C:
 [[3 2 1]]
D:
 [[1]
 [3]
 [5]]


In [9]:
# 矩阵相乘（*）
print('A*B:\n',A*B)
print('C*D:\n',C*D)

A*B:
 [[14 14 14]
 [32 32 32]
 [50 50 50]]
C*D:
 [[14]]


In [11]:
# 矩阵点乘（multiply）,维数必须相等
print(multiply(A,B))

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [20]:
# 矩阵求逆变换（.I）
a1 = mat(eye(2,2)*0.5)
print('a1:\n',a1)
a2 = a1.I
print('a2:\n',a2)

a1:
 [[0.5 0. ]
 [0.  0.5]]
a2:
 [[2. 0.]
 [0. 2.]]


In [21]:
#矩阵求转置（.T）
print('A.T:\n',A.T)

A.T:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
