In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
np.arange(10)[:,np.newaxis]*np.arange(10)[np.newaxis,:]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [6]:
import sklearn

In [7]:
[64]*3+[128]*4

[64, 64, 64, 128, 128, 128, 128]

In [8]:
a=1
def fu(a):
    print(a+4)

In [9]:
fu(2)

6


In [11]:
img = tf.io.read_file('style17.jpeg')

In [8]:
img.shape

TensorShape([1080, 1920, 3])

In [12]:
img = tf.image.decode_image(img,channels=3)

In [ ]:
img

In [9]:
img = tf.image.convert_image_dtype(img,tf.float32)

In [17]:
tf.shape(img)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1080, 1920,    3])>

In [16]:
tf.shape(img)[:-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1080, 1920])>