In [1]:
import tensorflow as tf



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os

In [5]:
np.arange(10)[:,np.newaxis]*np.arange(10)[np.newaxis,:]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [2]:
img = tf.io.read_file('style17.jpeg')
img = tf.image.decode_image(img, channels=3)
img = tf.image.convert_image_dtype(img, tf.float32)

In [3]:
shape = tf.cast(tf.shape(img)[:-1], tf.float32)

In [10]:
shape

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1080., 1920.], dtype=float32)>

In [7]:
max_dim = 1200
long_dim = max(shape)
scale = max_dim / long_dim

In [8]:
new_shape = tf.cast(shape * scale, tf.int32)

In [9]:
new_shape

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 675, 1200])>

In [2]:
tf.config.experimental.list_physical_devices(device_type='GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
print(os.environ['CUDA_VISIBLE_DEVICES'])

KeyError: 'CUDA_VISIBLE_DEVICES'

In [5]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [2]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
tf.__version__

'2.6.1'