In [1]:
import torch

In [34]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [35]:
y=x+2
z=y*y+3
print('z:\n',z)
out=z.mean()
print('out:\n',out)
out2=z.sum()
print('out2:\n',out2)

z:
 tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)
out:
 tensor(12., grad_fn=<MeanBackward0>)
out2:
 tensor(48., grad_fn=<SumBackward0>)


In [31]:
out.backward()

In [32]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [36]:
out2.backward()

In [37]:
print(x.grad)

tensor([[6., 6.],
        [6., 6.]])


In [38]:
with torch.no_grad():
    k=x+1
    print(k)

tensor([[2., 2.],
        [2., 2.]])
