In [1]:
import torch

In [2]:
torch.__version__

'1.10.2+cu113'

In [15]:
#定义向量
vector=torch.tensor([1,2,3,4])
print('vector:\t\t',vector)
print('vector shape:\t',vector.shape)

vector:		 tensor([1, 2, 3, 4])
vector shape:	 torch.Size([4])


In [19]:
#定义矩阵
matrix=torch.tensor([[1,2],[3,4],[5,6]])
print('matrix:\n',matrix)
print('matrix shape: ',matrix.shape)

matrix:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
matrix shape:  torch.Size([3, 2])


In [23]:
#定义张量
tensor=torch.tensor([[[1,2],[3,4],[5,6]]])
print('tensor:\n',tensor)
print('tensor shape: ',tensor.shape)

tensor:
 tensor([[[1, 2],
         [3, 4],
         [5, 6]]])
tensor shape:  torch.Size([1, 3, 2])


In [3]:
cuda_gpu = torch.cuda.is_available()
cuda_gpu

True

In [4]:
x=torch.randn(10,30)
y=x.cuda()

In [5]:
import time
s=time.process_time()
z1=x**x**x
e=time.proces

tensor([[-0.0208,  1.0996,  0.7191,  0.0853,  0.1504,  0.6204,  0.2179,  0.8529,
         -0.2139,  0.0652, -1.7631, -1.6472,  1.6476,  0.1303,  0.5188, -2.2594,
          0.1286,  0.6053,  1.1105, -1.2827,  0.5461, -0.2827,  1.7098,  2.0514,
          1.5674,  0.5944,  0.1240, -0.9329, -1.0201,  0.4281],
        [-0.8391,  0.7199,  2.0180, -0.6904, -0.8868, -1.0570,  0.9727, -0.6638,
         -0.3657, -1.6010,  0.6349,  1.0589,  0.0229,  1.1629,  0.1426, -0.9569,
          0.1223,  0.9284, -0.4064,  0.5747, -0.7669, -1.4341,  0.5409, -1.4959,
         -1.6521,  0.5461, -0.1674,  1.6404, -1.1822, -0.3221],
        [ 0.1111, -1.0036,  0.0806, -1.5237,  1.2981, -1.8262, -0.9087, -0.3465,
          0.8939, -0.6564,  1.1221, -0.2479,  0.0103, -0.6851, -0.8546, -1.4563,
         -1.7524,  0.5312, -0.0319,  1.1147, -0.4101, -0.5613, -0.8868, -0.6989,
          0.0153, -1.0088, -1.7626, -0.2513, -1.3266, -1.1498],
        [-0.0214,  1.3606,  1.4271,  0.1374, -0.7359,  0.9356, -0.5350, -0.3466