In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [13]:
class Net(nn.Module):
    def __init__(self):
        #定义神经网络结构，输入数据：1*32*32
        super(Net,self).__init__()
        #第一层：卷积层
        self.conv1=nn.Conv2d(1,6,3) #输入1层，输出6层，33的卷积核
        #第二层：卷积层
        self.conv2=nn.Conv2d(6,16,3)
        #第三层：全连接层
        self.fc1=nn.Linear(16*28*28,512) #16*28*28=12544
        #第四层：全连接层
        self.fc2=nn.Linear(512,64)
        #第五层：全连接层
        self.fc3=nn.Linear(64,2)
        pass
    
    def forward(self,x):
        #定义数据的流向
        x=self.conv1(x)
        x=F.relu(x)
        
        x=self.conv2(x)
        x=F.relu(x)
        
        x=x.view(-1,16*28*28)
        x=self.fc1(x)
        x=F.relu(x)
        
        x=self.fc2(x)
        x=F.relu(x)
        
        x=self.fc3(x)
        
        return x
    pass

In [14]:
net=Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)


In [15]:
#生成随机数据
input_data=torch.rand(1,1,32,32)
print(input_data)
print(input_data.shape)


tensor([[[[0.7862, 0.8964, 0.4521,  ..., 0.3917, 0.9104, 0.5559],
          [0.4300, 0.7227, 0.9387,  ..., 0.1354, 0.9128, 0.1052],
          [0.1397, 0.8436, 0.0162,  ..., 0.6412, 0.7090, 0.5238],
          ...,
          [0.5738, 0.6194, 0.9920,  ..., 0.0896, 0.8290, 0.3072],
          [0.9476, 0.5282, 0.5923,  ..., 0.2440, 0.4066, 0.1187],
          [0.0600, 0.7276, 0.6594,  ..., 0.4618, 0.1426, 0.3043]]]])
torch.Size([1, 1, 32, 32])


In [16]:
#运行神经网络
out=net(input_data)
print(out)
print(out.size())

tensor([[ 0.0625, -0.0652]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])


In [17]:
#随机生成真实值
target=torch.rand(2)
target=target.view(1,-1)
print(target)
print(target.size())

tensor([[0.7887, 0.5964]])
torch.Size([1, 2])


In [18]:
criterion=nn.L1Loss() #定义损失函数
loss=criterion(out,target) #计算损失
print(loss)

tensor(0.6939, grad_fn=<L1LossBackward0>)


In [19]:
net.zero_grad() #清零所有梯度
loss.backward() #自动计算梯度，反向传递

In [20]:
import torch.optim as optim
#优化权重
optimizer=optim.SGD(net.parameters(),lr=0.01)
optimizer.step()

In [21]:
#再次运行神经网络
out=net(input_data)
print(out)
print(out.size())

tensor([[ 0.0862, -0.0279]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])
