In [25]:
import h5py
import numpy as np
import pandas as pd

In [2]:
f = h5py.File("kappa5.hdf5")

<ipython-input-2-823c9e4cdc8b>:1: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  f = h5py.File("kappa5.hdf5")


In [3]:
list(f)

['frequency',
 'gamma',
 'group_velocity',
 'gv_by_gv',
 'heat_capacity',
 'kappa',
 'kappa_unit_conversion',
 'mesh',
 'mode_kappa',
 'qpoint',
 'temperature',
 'weight']

In [4]:
f['frequency'].shape

(455, 36)

In [5]:
f['gamma'].shape

(101, 455, 36)

In [31]:
f['gamma']

<HDF5 dataset "gamma": shape (101, 455, 36), type "<f8">

In [6]:
f['group_velocity'].shape

(455, 36, 3)

In [7]:
f['kappa'].shape

(101, 6)

In [10]:
f['temperature'].shape

(101,)

In [9]:
f['mode_kappa'].shape

(101, 455, 36, 6)

In [12]:
f['temperature'][:]

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,
        180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,
        270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,
        360.,  370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,
        450.,  460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,
        540.,  550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,
        630.,  640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,
        720.,  730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,
        810.,  820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,
        900.,  910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,
        990., 1000.])

In [14]:
f['kappa'][:,:]

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.87060527e+01,  6.69370568e+01,  1.93684497e+01,
         0.00000000e+00,  0.00000000e+00, -5.41349440e-17],
       [ 5.95567915e+00,  2.70130913e+01,  6.51757223e+00,
         0.00000000e+00,  0.00000000e+00, -1.16536155e-17],
       [ 3.26507286e+00,  1.60498446e+01,  3.70160979e+00,
         0.00000000e+00,  0.00000000e+00, -5.62100139e-18],
       [ 2.26739855e+00,  1.15172019e+01,  2.61776014e+00,
         0.00000000e+00,  0.00000000e+00, -3.62336052e-18],
       [ 1.75542533e+00,  9.06584781e+00,  2.04508900e+00,
         0.00000000e+00,  0.00000000e+00, -2.68105027e-18],
       [ 1.44107857e+00,  7.51991465e+00,  1.68677746e+00,
         0.00000000e+00,  0.00000000e+00, -2.14063656e-18],
       [ 1.22633384e+00,  6.44579734e+00,  1.43918806e+00,
         0.00000000e+00,  0.00000000e+00, -1.79001512e-18],
       [ 1.06921481e+00,  5.64995068e+00,  1.256

In [16]:
f['mode_kappa'][30,:]

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 9.56519363e-01,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 4.38384888e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.32665

In [17]:
f['group_velocity'][30,:,:]

array([[ 3.82965457e+00,  1.22154451e+01,  0.00000000e+00],
       [ 2.27631668e-01,  1.29724369e+01,  0.00000000e+00],
       [ 3.84116061e+00,  1.58997098e+01,  0.00000000e+00],
       [-1.48858470e+00,  1.07176797e+01,  0.00000000e+00],
       [-1.70160207e-01,  5.25142791e+00,  0.00000000e+00],
       [-2.32201943e+00,  4.94659715e+00,  0.00000000e+00],
       [ 2.83654904e+00,  3.56005986e+00,  0.00000000e+00],
       [ 1.39687450e+00,  1.22352146e+00,  0.00000000e+00],
       [ 1.07238159e+00,  9.61486854e+00,  0.00000000e+00],
       [ 3.49369042e+00,  4.32269939e+00,  0.00000000e+00],
       [-1.84551746e-02, -6.75885702e-01,  0.00000000e+00],
       [-1.03901597e+00,  9.69725431e-01,  0.00000000e+00],
       [ 5.40628979e-01,  1.73105899e+00,  0.00000000e+00],
       [-6.29389619e-01, -5.56391068e-02,  0.00000000e+00],
       [ 4.89717029e-01,  9.39717183e+00,  0.00000000e+00],
       [-7.79776014e-02,  8.77289213e+00,  0.00000000e+00],
       [-1.94493035e-01,  4.84667573e+00

In [19]:
g=f['gamma'][30]

In [20]:
g=np.where(g>0,g,-1)

In [21]:
lifetime=np.where(g>0,1.0/(2*2*np.pi*g),0)

In [24]:
lifetime

array([[ 0.        ,  0.        ,  0.        , ...,  4.82866118,
         2.75900842,  1.72485378],
       [23.43868004, 68.01732022, 45.584663  , ...,  3.89387359,
         2.48841197,  1.8306964 ],
       [17.54366349, 25.26523737, 18.52711621, ...,  4.11425342,
         2.73276661,  1.89137505],
       ...,
       [ 4.53204591,  4.53204591,  4.28320615, ...,  3.6367951 ,
         2.11101945,  2.11101945],
       [ 4.58009484,  4.58009484,  4.37929666, ...,  3.24908305,
         2.06364878,  2.06364878],
       [ 4.44986111,  4.44986111,  4.44986111, ...,  2.76720217,
         2.76720217,  2.76720217]])

In [26]:
lifetime_df=pd.DataFrame(lifetime)

In [27]:
lifetime_df

0          1          2          3          4         5   \
0     0.000000   0.000000   0.000000   5.917391  11.050556  4.860599   
1    23.438680  68.017320  45.584663   5.711009  10.683227  9.120663   
2    17.543663  25.265237  18.527116   5.434580  11.553923  8.208613   
3    15.887738  13.452861  12.479587   4.313186  10.895847  7.811504   
4     8.914820  17.662230   5.013059  11.986752  11.566261  7.982560   
..         ...        ...        ...        ...        ...       ...   
450   4.084214   4.084214   4.056688   4.056688   9.645981  9.645981   
451   4.284936   4.284936   4.024126   4.024126   9.337849  9.337849   
452   4.532046   4.532046   4.283206   4.283206   9.217218  9.217218   
453   4.580095   4.580095   4.379297   4.379297   8.959584  8.959584   
454   4.449861   4.449861   4.449861   4.449861   9.342058  9.342058   

            6          7         8         9   ...        26        27  \
0    12.414945   8.501373  3.320620  7.527183  ...  1.961027  1.950696   
1     4.683007   8.236871  3.947095  7.625868  ...  1.958838  1.918088   
2     4.978554   8.277611  7.695422  4.344039  ...  1.980764  1.912023   
3     5.465053   8.167045  7.502972  4.423217  ...  1.949798  1.869010   
4     5.836678   7.905846  7.767627  4.455174  ...  1.899378  1.874756   
..         ...        ...       ...       ...  ...       ...       ...   
450  12.073604  12.073604  4.314777  4.314777  ...  3.038921  3.038921   
451  11.730195  11.730195  4.991661  4.991661  ...  3.103011  3.103011   
452  11.160006  11.160006  5.496253  5.496253  ...  3.195589  3.195589   
453  10.285729  10.285729  5.737897  5.737897  ...  3.184117  3.184117   
454   9.342058   9.342058  5.860172  5.860172  ...  3.024420  3.024420   

           28        29        30        31        32        33        34  \
0    3.544953  4.497185  6.195485  5.151222  7.944632  4.828661  2.759008   
1    3.554792  4.546797  6.123288  5.297530  7.107688  3.893874  2.488412   
2    3.592069  4.574821  4.968480  5.964592  3.577050  4.114253  2.732767   
3    3.679514  4.394005  4.556583  5.710609  3.294439  2.921249  2.894127   
4    3.737943  4.583303  4.178899  5.259827  2.792758  2.616209  3.066449   
..        ...       ...       ...       ...       ...       ...       ...   
450  3.712799  3.712799  3.175515  3.175515  4.235036  4.235036  2.256993   
451  3.683104  3.683104  3.064794  3.064794  4.036404  4.036404  2.088409   
452  3.630118  3.630118  2.931398  2.931398  3.636795  3.636795  2.111019   
453  3.496855  3.496855  3.036174  3.036174  3.249083  3.249083  2.063649   
454  3.226750  3.226750  3.226750  3.226750  2.767202  2.767202  2.767202   

           35  
0    1.724854  
1    1.830696  
2    1.891375  
3    2.006743  
4    2.325329  
..        ...  
450  2.256993  
451  2.088409  
452  2.111019  
453  2.063649  
454  2.767202  

[455 rows x 36 columns]

NameError: name 'plt' is not defined